config/routes.rb
Appzilla::Application.routes.draw do
  resources :high_scores

  root :to => 'home#index'
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @high_score }
      else
        format.html { render action: 'new' }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
        <td><%= high_score.game %></td>
        <td><%= high_score.score %></td>
        <td><%= link_to 'Show', high_score %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/home/index.html.erb
<div class="container-fluid hidden-phone custom-fluid-cont">
    <div class="row-fluid">
        <div id="da-slider" class="da-slider">
            <div class="da-slide">
                <h1>where da hoes?</h1>
                <p>Find out why you simply cannot live without our product. It's so cool, you'll tell your parents about it and explain it to them several times without getting annoyed. We promise we won't let you down. Try us out!</p>
                <a href="#" class="da-link">Read more &rarr;</a>
                <div class="da-img"><img src="img/4.png" alt="image01" /></div>
            </div>
            <div class="da-slide">
                <h1>Feature packed</h1>
                <p>We have so many features that our office has a special storage floor just for them. They aren't noisy or anything like that, but there's just so many of them we don't have a better place to put them.</p>
                <a href="#" class="da-link">Read more &rarr;</a>
                <div class="da-img"><img src="img/2.png" alt="image01" /></div>
            </div>
            <div class="da-slide">
                <h1>This is the third slide</h1>
                <p>If you got this far, there's a chance you really like our theme. Be sure to check out all the really nice pages we've added for you and don't hesitate in shooting us a question if you need anything cleared. Have fun!</p>
                <a href="#" class="da-link">Read more &rarr;</a>
                <div class="da-img"><img src="img/3.png" alt="image01" /></div>
            </div>
            <nav class="da-arrows">
                <span class="da-arrows-prev"></span>
                <span class="da-arrows-next"></span>
            </nav>
        </div>
    </div><!-- /row-fluid -->
</div><!-- /container-fluid -->

<div class="container">
    <div class="row ">
        <div class="page-header span12">
            <h2>StartupTheme is trusted by over 9000 customers world wide. <a href="tour.html">Take the tour</a> now to find out why!</h2>
        </div>
    </div><!-- /row -->

    <div class="row top-space">
        <div class="span4">
            <h3><i class="icon-cogs icon-large baseline" style="font-size:16px"></i>&nbsp; Optimization</h3>
            <p>We made sure every piece of Javascript and CSS is optimized. Additionally you can combine styles and scripts so your site won't make unnecessary HTTP requests.</p>
        </div>
        <div class="span4">
            <h3><i class="icon-fullscreen icon-large baseline" style="font-size:16px"></i>&nbsp; Responsive design</h3>
            <p>Either in a phone, tablet, laptop or desktop, the design will be perfectly optimized. Our components are scaled according to a range of resolutions and devices to provide a consistent experience, no matter what.</p>
        </div>
        <div class="span4">
            <h3><i class="icon-user icon-large baseline" style="font-size:16px"></i>&nbsp; Make it your own</h3>
            <p>While the design is beautiful out of the box, we made sure you can give it your personal touch without breaking a sweat. From the carousel to the styles, the code is organized neatly so you have a nice time tweaking it.</p>
        </div>
    </div><!-- /row -->
    <div class="row top-space">
        <div class="span4">
            <h3><i class="icon-sitemap icon-large baseline" style="font-size:16px"></i>&nbsp; Organization</h3>
            <p>Optimizing the space with a reasonable ratio between style and substance StartupTheme offers you a lot of flexibility to present and organize your content. Make sure your message is heard.</p>
        </div>
        <div class="span4">
            <h3><i class="icon-group icon-large baseline" style="font-size:16px"></i>&nbsp; Friendly Support</h3>
            <p>Just shoot us an email and we'll be glad to give you a hand with anything you need. Or just say hi!</p>
        </div>
        <div class="span4">
            <h3><i class="icon-retweet icon-large baseline" style="font-size:16px"></i>&nbsp; User Convertion</h3>
            <p>With a clean design you'll be more likely to keep users untill they've read what you have to offer. Having a disorganized page scares away users and is awful for your brand.</p>
        </div>
    </div><!-- /row -->
    <br />
    <div class="row hidden-phone">
        <div class="span12">
            <h3>The press we haven't got can't stop not talking about us</h3>
        </div>
    </div>
    <div class="row top-space hidden-phone">
        <div class="span3">
            <a href="#"><div class="press techcrunch hidden-tablet"></div></a>
        </div>
        <div class="span3">
            <a href="#" class="press webbys"></a>
        </div>
        <div class="span3">
            <a href="#" class="press lifehacker"></a>
        </div>
        <div class="span3">
            <a href="#" class="press betakit"></a>
        </div>
    </div><!-- /row -->
    <div class="row top-space">
        <div class="span12 top-space">
            <div class="hero-unit">
                <h1>StartupTheme is what you've been waiting for. <small><a href="plans.html">Check out our plans</a> and find out which one best fits <strong>your</strong> needs!</small></h1>
            </div>
        </div>
    </div>
</div><!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appzilla</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar">
    <div class="navbar-inner custom-navbar">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
            <a class="brand custom-brand" href="index.html">
                <!-- image brand -->
                    <!-- <img src="img/logo.png" alt="Super slogan"> -->
                <!-- text brand -->
                StartupTheme<span class="brand-color">.</span>
            </a>
            <div class="nav-collapse in" style="height:auto;">
                <ul class="nav pull-right">
                    <li><a class="active" href="index.html">Home</a></li>
                    <li><a href="tour.html">Tour</a></li>
                    <li><a href="plans.html">Plans</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!-- /container -->
    </div>
</div><!-- /navbar -->


<%= yield %>


<footer>
<div class="container">
    <div class="row">
        <div class="span3">
            <h4>Latest Blog Post</h4><br />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus suscipit nisl ac metus porta placerat... <a href="#">Read more &rarr;</a></p>
        </div>
        <div class="span3">
            <h4>Quick Links</h4><br />
            <div class="row">
                <div class="span1">
                    <ul class="unstyled">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="tour.html">Tour</a></li>
                        <li><a href="#">Help Desk</a></li>
                    </ul>
                </div>
                <div class="span1">
                    <ul class="unstyled">
                        <li><a href="plans.html">Plans</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="#">Privacy</a></li>
                    </ul>
                </div>
                <div class="span1">
                    <ul class="unstyled">
                        <li><a href="about.html">About</a></li>
                        <li><a href="contact.html">Contact</a></li>
                        <li><a href="#">Terms</a></li>
                    </ul>
                </div>
            </div><!-- /row -->
        </div>
        <div class="span3">
            <h4>Contact Us!</h4><br />
            <address>
                <strong>StartupTheme, Inc.</strong><br />
                795 Sea of Tranquility, Suite 600<br />
                The Moon, MOON 94107
            </address>
        </div>
        <div class="span3">
            <h4>Newsletter</h4><br />
            <p>Subscribe to our newsletter!</p>
            <form id="form" class="form-inline">
                <input type="text" value="" name="email" class="input-medium email" id="email" placeholder="Your email address">
                <input type="submit" value="Subscribe" name="subscribe" class="btn btn-primary">
            </form>
        </div>
    </div><!-- /row -->
</div><!-- /container -->

<div class="final-footer">
    <div class="container">
        <div class="row">
            <div class="span4">
                <p>&copy; <a href="#">StartupTheme</a> 2012, all right reserved.</p>
            </div>
            <div class="span8">
                <ul class="footer-ul pull-right">
                    <li class="inline"><a href="#">Help Desk</a></li>
                    <li class="inline"><a href="#">Privacy Policy</a></li>
                    <li class="inline"><a href="#">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
</footer>

<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery-1.7.2.js"></script>
<script type="text/javascript" src="js/jquery.validate.js"></script>
<script type="text/javascript" src="js/bootstrap-collapse.js"></script>
<script type="text/javascript" src="js/bootstrap-tooltip.js"></script>
<script src="js/jquery.cslider.js"></script>
<script type="text/javascript">
$('#da-slider').cslider({
    current     : 0,
    bgincrement : 50, // parallax
    autoplay    : true,
    interval    : 5000
});
$(document).ready(function(){
    $("#form").validate({
        rules: {
            email: "required",
        },
        highlight: function(element, errClass) {
            $("#email").tooltip('show');
        },
        unhighlight: function(element, errClass) {
            $("#email").tooltip('hide');
        },
        errorPlacement: function(err, element) {
            err.hide();
        },
    });
    $("#email").tooltip({
        placement: 'bottom',
        trigger: 'manual',
        title: 'Please insert a valid email address!',
    });
});
</script>




</body>
</html>